- name: Deploy borg remote
  hosts: remote
  vars:
    - ansible_become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install borg
      get_url:
        url: "https://github.com/borgbackup/borg/releases/download/1.2.4/borg-linux64"
        dest: /usr/local/bin/borg
        mode: 0755
        owner: root
        group: root

    - name: Create borg user
      user:
        name: "borg"
        create_home: yes
        generate_ssh_key: true

    - name: Add vinculum to authorized keys
      authorized_key:
        key: "{{ lookup('file', 'vinculum/id_ed25519.pub') }}"
        user: borg
        key_options: "command=\"borg serve\",restrict"

    - name: Add drone to authorized keys
      authorized_key:
        key: "{{ lookup('file', 'drone/id_ed25519.pub') }}"
        user: borg
        key_options: "command=\"borg serve --append-only --restrict-to-repository 1_of_9\",restrict"
