- name: Deploy borg remote
  hosts: remote
  vars:
    - ansible_become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install borg
      get_url:
        url: "https://github.com/borgbackup/borg/releases/download/1.2.3/borg-linux64"
        dest: /usr/local/bin/borg
        mode: 0755
        owner: root
        group: root

    - name: Create borg user
      user:
        name: "borg"
        create_home: yes
        generate_ssh_key: true
